import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://video-react.github.io/assets/video-react.css"
        />
      </Head>

      <main>
        <h1 className="text-8xl uppercase">Course Plug</h1>
        <video controls style={{ width: "400px" }}>
          <source src="/1.mp4" type="video/mp4" />
        </video>
      </main>
    </div>
  );
}
