import { Dialog } from "@headlessui/react";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  let [isOpen, setIsOpen] = useState(true);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://video-react.github.io/assets/video-react.css"
        />
      </Head>

      <main>
        <iframe
          className="sproutvideo-player"
          src="https://videos.sproutvideo.com/embed/a79ed8b71d1ce4c52e/79cbec35885693ac"
          width="400"
          height="224"
          referrerpolicy="no-referrer-when-downgrade"
        ></iframe>

        <iframe
          className="sproutvideo-player"
          src="https://videos.sproutvideo.com/embed/069ed8b71d1de5c08f/ad6cfd02ad1ad87a"
          width="400"
          height="224"
          allowfullscreen
          referrerpolicy="no-referrer-when-downgrade"
        ></iframe>
      </main>
    </div>
  );
}
